spring:
  application:
    name: organization-service
  cloud:
    loadbalancer:
      health-check:
        interval: 15s
    consul:
      discovery:
        tags: group=eb_lab
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

server:
  port: 11402